### ISSUE TITLE
Missing test() definition

### ISSUE THREAD

**Issue by FredWe** [vra/vra.github.io#1]
https://github.com/vra/vra.github.io/blob/aedb2a0650b372ffa509af384ac3ea00e43ca178/2022/05/19/pytorch-mps-benchmark/index.html#L127

Line 113 refer to a test()
`   test(model, device, test_loader)`

but it is not defined before.

**Comment by vra** [comment]
Hi @FredWe ,
Thanks for pointing this out. I will check and fix it after work.

**Comment by vra** [comment]
Code updated. please check it out, thanks
